development:
  adapter: postgresql
  encoding: unicode
  database: pickemup_scraper_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: pickemup_scraper_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: pickemup_scraper_production
  pool: 5
  host: localhost
